In [13]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, roc_auc_score

# Load Dataset
data = pd.read_csv(".csv")

# Display first few rows
data.head()

# Data Exploration and Preprocessing
print(data.info())  # Check data types and missing values

FileNotFoundError: [Errno 2] No such file or directory: 'spaceship_titanic.csv'

In [11]:
# Display first few rows
data.head()

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation
0,Aachen,1,Valid,L5,21.0,Fell,1880-01-01T00:00:00.000,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951-01-01T00:00:00.000,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952-01-01T00:00:00.000,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976-01-01T00:00:00.000,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902-01-01T00:00:00.000,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [4]:
data

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation
0,Aachen,1,Valid,L5,21.0,Fell,1880-01-01T00:00:00.000,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951-01-01T00:00:00.000,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952-01-01T00:00:00.000,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976-01-01T00:00:00.000,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902-01-01T00:00:00.000,-33.16667,-64.95000,"(-33.16667, -64.95)"
...,...,...,...,...,...,...,...,...,...,...
995,Tirupati,24009,Valid,H6,230.0,Fell,1934-01-01T00:00:00.000,13.63333,79.41667,"(13.63333, 79.41667)"
996,Tissint,54823,Valid,Martian (shergottite),7000.0,Fell,2011-01-01T00:00:00.000,29.48195,-7.61123,"(29.48195, -7.61123)"
997,Tjabe,24011,Valid,H6,20000.0,Fell,1869-01-01T00:00:00.000,-7.08333,111.53333,"(-7.08333, 111.53333)"
998,Tjerebon,24012,Valid,L5,16500.0,Fell,1922-01-01T00:00:00.000,-6.66667,106.58333,"(-6.66667, 106.58333)"
999,Tomakovka,24019,Valid,LL6,600.0,Fell,1905-01-01T00:00:00.000,47.85000,34.76667,"(47.85, 34.76667)"

In [5]:
# 2. Data Exploration and Preprocessing
# Check for missing values
print(data.isnull().sum())

name            0
id              0
nametype        0
recclass        0
mass           28
fall            0
year            1
reclat         12
reclong        12
geolocation    12
dtype: int64

In [12]:
# Pairplot for mass, latitude, and longitude by meteorite type
sns.pairplot(data[['mass (g)', 'reclat', 'reclong', 'type']], hue='type', palette='coolwarm')
plt.suptitle('Pairplot of Meteorite Features by Type (Stony vs Iron)', y=1.02)
plt.show()

# Visualize the geographical distribution of meteorite landings (Stony vs Iron)
plt.figure(figsize=(10, 6))
sns.scatterplot(x=data['reclong'], y=data['reclat'], hue=data['type'], palette='coolwarm')
plt.title('Geographical Distribution of Meteorite Landings')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.show()

KeyError: "['mass (g)', 'type'] not in index"